services:
  web:
    image: nginx:latest
    #working_dir: /usr/share/nginx/html/
    volumes:
      - ./public:/usr/share/nginx/html/
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx/error.log:/var/www/log/error.log
      - ./log/nginx/access.log:/var/www/log/access.log
    ports:
      - 80:80
    networks:
      - app-network
  
  php:
    image: my/php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_HOST: "${DB_HOST:-db}"
      PAGBANK_API: "${PAGBANK_API}"
      PAGBANK_API_TOKEN: "${PAGBANK_API_TOKEN}"
      
  db:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_USER: "${MYSQL_ROOT_USER}"
      MYSQL_TCP_PORT: "${DB_PORT:-3306}"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
