<div class="container">
    <form action="/admin/products" method="post">
        <?php include ROOT_PATH . '/app/views/components/csrf.phtml'; ?>
        <div class="form-row">
            <div class="form-gourp col-md-6 col-12">
                <label for="title">Title</label>
                <input type="text" name="title" id="title" class="form-control" required/>
            </div>
            <div class="form-group col-md-6 col-12">
                <label for="price">Price</label>
                <input type="number" name="price" min="0.00" max="10000.00" step="0.01" id="price" class="form-control" required>
            </div>
        </div>

        <div class="from-gourp mb-4">
            <label for="description">Description</label>
            <input type="text" name="description" id="description" class="form-control form-control-lg" required>
        </div>


        <div class="form-group container row offset-md-4">
            <input type="submit" value="create" id="submit" class="btn btn-primary col-md-4 col-12">
        </div>
        
    </form>
</div>