<?php include ROOT_PATH . '/app/views/components/flashCard.phtml'; ?>
<nav>
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/admin/products">products</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/admin/productVariants">new product Variant</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Desativado</a>
  </li>
</ul>
</nav>