<div class="container">
    <div class=" container card">
        <form action="/admin/login" method="post">
            <?php include ROOT_PATH . '/app/views/components/csrf.phtml'; ?>
            <div class="form-group">
                <label for="name" class="form-label">Name</label>
                <input type="text" name="name" id="name" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
            <div class="form-group">
                <input type="submit" value="login" id="submit" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
