<?php include ROOT_PATH . '/app/views/components/flashCard.phtml'; ?>

<div class="container">
  <div class="container row offset-md-0 mb-2">
      <a href="/admin/products/create" class="btn btn-primary col-md-2 col-12">
        new product
      </a>
  </div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">price</th>
        <th scope="col">Status</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($products as $product):?>
          <tr>
            <th scope="row"><?=$product->getId()?></th>
            <td><?=$product->getTitle()?></td>
            <td><?='R$ ' . number_format($product->getPrice() / 100.0,2)?></td>
            <td><?=$product->getStatus()?></td>
            <td><a href="/admin/products/<?= $product->getId()?>" class="btn">edit</a></td>
          </tr>
      <?endforeach;?>
  </table>
</div>
