<?php include ROOT_PATH . '/app/views/components/flashCard.phtml'; ?>
<div class="container">
    <div class="row container scroller">
        <?php foreach ($items as $item) :
            $product = $item->getProduct();
            $variant = $item->getVariant();
            $grid = $variant->getGrid();
            $grid = explode('/', $grid);
            // print_r($grid);
            // var_dump($product);
            // var_dump($variant);
        ?>
            <div class="col-12 row border p-4">
                <div class="col-sm-6 col-12 container-fluid">
                    <img src="<?= $item->getImage() ?>" alt="" class="img-fluid">
                </div>
                <div class="col-sm-6 col-12">
                    <h5><?= $product->getTitle() ?></h5>
                    <div class="row">
                        <div class="col-4">
                            <?= $grid[0] ?>
                        </div>
                        <div class="col-4 border-left">
                            <?=$grid[1] ?>
                        </div>
                        <div class="col-4 border-left">
                            <?= $grid[2] ?>
                        </div>
                    </div>
                    <div class="row">

                        <label for="quantity" class="col-12">Quantity</label>
                        <div class="input-group col-12">
                            <input type="number" name="quantity" id="quantity" class="form-control" min="0" value="<?= $item->getItemQuantity()?>">
                            <div class="input-group-append">
                                <span class="input-group-text max-quantity"><?= $variant->getStockQantity()?></span>
                            </div>
                        </div>
                    </div>
                    <div>
                        price: R$ <?= number_format($variant->getPrice() / 100,2)?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>