<section class="container">
    <div class="row">
        <?php foreach ($products as $product):?>
            <div class="border col-gl-3 col-md-4 col-sm-6 col-12 p-4">
                <div class="h-50 overflow-hiden">
                    <a href="/product/<?= $product->getId()?>">
                        <img src="<?= $product->getImages()[0]?>" alt="<?= $product->getTitle()?>" class="mw-100">
                    </a>
                </div>
                <div class="h-50 overflow-hiden d-flex flex-column justify-content-around flex-fill">
                    <div class="mb-4">
                        <a href="/product/<?= $product->getId()?>" class="flex-fill">
                            <div class=" h4">
                                <?= $product->getTitle()?>
                            </div>
                        </a>
                    </div>
                    <div class="h4">
                        R$ <?= number_format($product->getPrice() / 100.0,2)?>
                    </div>
                    <div class="flex-fill">
                        <?= $product->getDescription()?>
                    </div>
                </div>
            </div>
        <?endforeach;?>
    </div>
    <nav>
        <ul class="pagination">
            <li class="page-item <?= $curentPage == 1 ? 'disabled' : ''?>">
                <a class="page-link" href="/home/<?= $curentPage == 1 ? 1 : $curentPage - 1?>">Previusly</a>
            </li>
                <?php 
                    $min =  $curentPage > 2 ? $curentPage - 2 : 1;
                    $max = ($pageTotal - $curentPage) >= 2 ? $curentPage + 2 : $pageTotal;
                    for ($i = $min; $i <= $max ; $i++) {
                        echo '<li class="page-item ' . ($curentPage == $i ? 'active' : '') . '">' .
                        '<a class="page-link" href="/home/?ps=12&pn=' . $i 
                        . (isset($search) ? "&search=$search": '') . '">' . $i . '</a></li>';
                    }
                ?>
            <li class="page-item">
                <a class="page-link" href="/home?ps=12&pn=<?= $curentPage == $pageTotal ? $pageTotal : $curentPage + 1?>">Nex</a>
            </li>
        </ul>
    </nav>
</section>