<!Doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<link rel="stylesheet" type="text/css" href="/assets/css/lib/bootstrep.min.css">
<link rel="stylesheet" type="text/css" href="/assets/css/application.css">

<body>
    <?php include_once ROOT_PATH . '/app/views/components/header.phtml'?>
    <?php include_once ROOT_PATH . '/app/views/components/flashCard.phtml'; ?>
    <?php require $view ?>
</body>
<script src="/assets/js/lib/jquery-3.3.1.slim.min.js"></script>
<script src="/assets/js/lib/jquery.mask.min.js"></script>
<script src="/assets/js/lib/popper.min.js"></script>
<script src="/assets/js/lib/bootstrap.min.js"></script>
<script type="module" src="/assets/js/index.js"></script>
</html>